all:
	gcc -o main codes/main.c codes/arquivo.c codes/funcionalidades.c codes/funcoesFornecidas.c codes/funcoes.c codes/leitura.c codes/registro.c codes/funcoesGrafos.c codes/criaGrafos.c

run:
	./main